// Definición de los campos que el editor muestra después del pago,
// por categoría. Cada diseño puede usar el esquema base tal cual o
// agregar/quitar campos propios.

const bodaSchema = [
  { name: "novia", label: "Nombre de la novia", type: "text", required: true },
  { name: "novio", label: "Nombre del novio", type: "text", required: true },
  { name: "fecha", label: "Fecha del casamiento", type: "date", required: true },
  { name: "horaCeremonia", label: "Hora de la ceremonia", type: "time" },
  { name: "lugarCeremonia", label: "Lugar de la ceremonia", type: "text" },
  { name: "horaFiesta", label: "Hora de la fiesta", type: "time" },
  { name: "lugarFiesta", label: "Lugar de la fiesta", type: "text" },
  { name: "direccionMapa", label: "Link de Google Maps", type: "url" },
  { name: "mensaje", label: "Mensaje / frase para los invitados", type: "textarea" },
  { name: "dressCode", label: "Código de vestimenta", type: "text" },
  { name: "alias", label: "Alias / CBU para regalo", type: "text" },
  { name: "whatsapp", label: "WhatsApp para RSVP (código país + número)", type: "text" },
  { name: "fechaLimiteRSVP", label: "Fecha límite para confirmar asistencia", type: "date" },
  { name: "musica", label: "Música de fondo", type: "music", feature: "musica" },
  { name: "aliasPersonalizado", label: "Alias personalizado para tu link (opcional, ej: julieta-y-tomas)", type: "text", feature: "alias" },
  { name: "videoPortada", label: "Video de portada", type: "video", feature: "video" },
  { name: "multilenguaje", label: "Mostrar invitación también en inglés", type: "checkbox", feature: "multilenguaje" },
  { name: "colorPalette", label: "Gama de colores", type: "palette" },
  { name: "coverImage", label: "Foto de portada", type: "image" },
  { name: "galeria", label: "Galería de fotos", type: "images" },
];

const xvSchema = [
  { name: "nombre", label: "Nombre de la quinceañera", type: "text", required: true },
  { name: "fecha", label: "Fecha de la fiesta", type: "date", required: true },
  { name: "horaCeremonia", label: "Hora de la ceremonia (opcional)", type: "time" },
  { name: "lugarCeremonia", label: "Lugar de la ceremonia (opcional)", type: "text" },
  { name: "horaFiesta", label: "Hora de la fiesta", type: "time" },
  { name: "lugarFiesta", label: "Lugar de la fiesta", type: "text" },
  { name: "direccionMapa", label: "Link de Google Maps", type: "url" },
  { name: "padres", label: "Padres", type: "text" },
  { name: "mensaje", label: "Mensaje para los invitados", type: "textarea" },
  { name: "dressCode", label: "Código de vestimenta", type: "text" },
  { name: "whatsapp", label: "WhatsApp para RSVP", type: "text" },
  { name: "fechaLimiteRSVP", label: "Fecha límite para confirmar asistencia", type: "date" },
  { name: "musica", label: "Música de fondo", type: "music", feature: "musica" },
  { name: "aliasPersonalizado", label: "Alias personalizado para tu link (opcional, ej: julieta-y-tomas)", type: "text", feature: "alias" },
  { name: "videoPortada", label: "Video de portada", type: "video", feature: "video" },
  { name: "multilenguaje", label: "Mostrar invitación también en inglés", type: "checkbox", feature: "multilenguaje" },
  { name: "colorPalette", label: "Gama de colores", type: "palette" },
  { name: "coverImage", label: "Foto de portada", type: "image" },
  { name: "galeria", label: "Galería de fotos", type: "images" },
];

const cumpleanosSchema = [
  { name: "nombre", label: "Nombre del cumpleañero/a", type: "text", required: true },
  { name: "edad", label: "Edad que cumple (opcional)", type: "text" },
  { name: "fecha", label: "Fecha de la fiesta", type: "date", required: true },
  { name: "hora", label: "Hora", type: "time" },
  { name: "lugar", label: "Lugar", type: "text" },
  { name: "direccionMapa", label: "Link de Google Maps", type: "url" },
  { name: "mensaje", label: "Mensaje para los invitados", type: "textarea" },
  { name: "dressCode", label: "Código de vestimenta (opcional)", type: "text" },
  { name: "whatsapp", label: "WhatsApp para RSVP (código país + número)", type: "text" },
  { name: "fechaLimiteRSVP", label: "Fecha límite para confirmar asistencia", type: "date" },
  { name: "musica", label: "Música de fondo", type: "music", feature: "musica" },
  { name: "colorPalette", label: "Gama de colores", type: "palette" },
  { name: "coverImage", label: "Foto de portada", type: "image" },
  { name: "galeria", label: "Galería de fotos", type: "images" },
];

const infantilSchema = [
  { name: "nombreChico", label: "Nombre del cumpleañero/a", type: "text", required: true },
  { name: "edad", label: "Edad que cumple", type: "text", required: true },
  { name: "fecha", label: "Fecha de la fiesta", type: "date", required: true },
  { name: "hora", label: "Hora", type: "time" },
  { name: "lugar", label: "Lugar", type: "text" },
  { name: "direccionMapa", label: "Link de Google Maps", type: "url" },
  { name: "mensaje", label: "Mensaje para los invitados", type: "textarea" },
  { name: "tematica", label: "Temática / disfraz sugerido (opcional)", type: "text" },
  { name: "whatsapp", label: "WhatsApp para RSVP (código país + número)", type: "text" },
  { name: "fechaLimiteRSVP", label: "Fecha límite para confirmar asistencia", type: "date" },
  { name: "musica", label: "Música de fondo", type: "music", feature: "musica" },
  { name: "colorPalette", label: "Gama de colores", type: "palette" },
  { name: "coverImage", label: "Foto de portada", type: "image" },
  { name: "galeria", label: "Galería de fotos", type: "images" },
];

const bautismoSchema = [
  { name: "nombreChico", label: "Nombre del bautizado/a", type: "text", required: true },
  { name: "padres", label: "Padres", type: "text" },
  { name: "padrinos", label: "Padrinos", type: "text" },
  { name: "fecha", label: "Fecha", type: "date", required: true },
  { name: "horaCeremonia", label: "Hora de la ceremonia", type: "time" },
  { name: "lugarCeremonia", label: "Lugar de la ceremonia", type: "text" },
  { name: "horaFiesta", label: "Hora de la fiesta (opcional)", type: "time" },
  { name: "lugarFiesta", label: "Lugar de la fiesta (opcional)", type: "text" },
  { name: "direccionMapa", label: "Link de Google Maps", type: "url" },
  { name: "mensaje", label: "Mensaje para los invitados", type: "textarea" },
  { name: "whatsapp", label: "WhatsApp para RSVP", type: "text" },
  { name: "fechaLimiteRSVP", label: "Fecha límite para confirmar asistencia", type: "date" },
  { name: "musica", label: "Música de fondo", type: "music", feature: "musica" },
  { name: "colorPalette", label: "Gama de colores", type: "palette" },
  { name: "coverImage", label: "Foto de portada", type: "image" },
  { name: "galeria", label: "Galería de fotos", type: "images" },
];

const saveTheDateSchema = [
  { name: "novia", label: "Nombre de la novia", type: "text", required: true },
  { name: "novio", label: "Nombre del novio", type: "text", required: true },
  { name: "fecha", label: "Fecha (aunque sea tentativa)", type: "date", required: true },
  { name: "lugar", label: "Ciudad / lugar donde va a ser", type: "text" },
  { name: "mensaje", label: "Mensaje corto para los invitados", type: "textarea" },
  { name: "instagram", label: "Instagram del evento (opcional)", type: "text" },
  { name: "whatsapp", label: "WhatsApp de contacto (opcional)", type: "text" },
  { name: "musica", label: "Música de fondo", type: "music", feature: "musica" },
  { name: "colorPalette", label: "Gama de colores", type: "palette" },
  { name: "coverImage", label: "Foto de portada", type: "image" },
  { name: "galeria", label: "Galería de fotos (opcional)", type: "images" },
];

const halloweenSchema = [
  { name: "nombre", label: "Nombre del cumpleañero/a o anfitrión/es", type: "text", required: true },
  { name: "fecha", label: "Fecha", type: "date", required: true },
  { name: "hora", label: "Hora", type: "time" },
  { name: "lugar", label: "Lugar", type: "text" },
  { name: "direccionMapa", label: "Link de Google Maps", type: "url" },
  { name: "mensaje", label: "Mensaje para los invitados", type: "textarea" },
  { name: "disfraz", label: "Consigna de disfraz (opcional)", type: "text" },
  { name: "whatsapp", label: "WhatsApp para RSVP", type: "text" },
  { name: "fechaLimiteRSVP", label: "Fecha límite para confirmar asistencia", type: "date" },
  { name: "musica", label: "Música de fondo", type: "music", feature: "musica" },
  { name: "colorPalette", label: "Gama de colores", type: "palette" },
  { name: "coverImage", label: "Foto de portada", type: "image" },
  { name: "galeria", label: "Galería de fotos", type: "images" },
];

const navidadSchema = [
  { name: "nombre", label: "Nombre del festejo o anfitrión/es", type: "text", required: true },
  { name: "fecha", label: "Fecha", type: "date", required: true },
  { name: "hora", label: "Hora", type: "time" },
  { name: "lugar", label: "Lugar", type: "text" },
  { name: "direccionMapa", label: "Link de Google Maps", type: "url" },
  { name: "mensaje", label: "Mensaje para los invitados", type: "textarea" },
  { name: "amigoInvisible", label: "Amigo invisible / qué traer (opcional)", type: "text" },
  { name: "whatsapp", label: "WhatsApp para RSVP", type: "text" },
  { name: "fechaLimiteRSVP", label: "Fecha límite para confirmar asistencia", type: "date" },
  { name: "musica", label: "Música de fondo", type: "music", feature: "musica" },
  { name: "colorPalette", label: "Gama de colores", type: "palette" },
  { name: "coverImage", label: "Foto de portada", type: "image" },
  { name: "galeria", label: "Galería de fotos", type: "images" },
];

module.exports = {
  bodaSchema, xvSchema, cumpleanosSchema, infantilSchema, bautismoSchema,
  saveTheDateSchema, halloweenSchema, navidadSchema,
};
